// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rxkX1XyVYLUh7MYQGN3-6Znd2WDxmcw',
    appId: '1:900801684873:web:0a3f323218e6ea5325ed58',
    messagingSenderId: '900801684873',
    projectId: 'clubhub-52543',
    authDomain: 'clubhub-52543.firebaseapp.com',
    storageBucket: 'clubhub-52543.firebasestorage.app',
    measurementId: 'G-7YZ4P9WLHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UY1GDDZSrsDnAaT3_7inkJVQ92n-PkM',
    appId: '1:900801684873:android:bf53183f58e0bc3725ed58',
    messagingSenderId: '900801684873',
    projectId: 'clubhub-52543',
    storageBucket: 'clubhub-52543.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCYgX0oYdsar9rsEtIItqSLgsixznrEA',
    appId: '1:900801684873:ios:ad15364be92743e325ed58',
    messagingSenderId: '900801684873',
    projectId: 'clubhub-52543',
    storageBucket: 'clubhub-52543.firebasestorage.app',
    iosBundleId: 'com.example.clubhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCYgX0oYdsar9rsEtIItqSLgsixznrEA',
    appId: '1:900801684873:ios:ad15364be92743e325ed58',
    messagingSenderId: '900801684873',
    projectId: 'clubhub-52543',
    storageBucket: 'clubhub-52543.firebasestorage.app',
    iosBundleId: 'com.example.clubhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-rxkX1XyVYLUh7MYQGN3-6Znd2WDxmcw',
    appId: '1:900801684873:web:2e233611256f515025ed58',
    messagingSenderId: '900801684873',
    projectId: 'clubhub-52543',
    authDomain: 'clubhub-52543.firebaseapp.com',
    storageBucket: 'clubhub-52543.firebasestorage.app',
    measurementId: 'G-WL1V82SS10',
  );

}